### ISSUE TITLE
ntpath.py TypeError: expected str, bytes, or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Lucysmith8** [anthony-tuininga/cx_Freeze#672]
I am trying to read an H5 file from a folder called module.

In the folder, I have the file read.py, which allows to import the H5 module with the following code:

    from .model import model_h5

    

    model = load_model(model_h5)

The model is imported from another file and another folder \model\__init__.py. Inside model folder there __init__.py and model.h5

    from os import path

    import sys

    

    if getattr(sys, 'frozen', False):

        MODEL_DIRECTORY = path.join(path.dirname(sys.executable), 'model')

    else:

        MODEL_DIRECTORY = path.dirname(__file__)

        

        

    model_h5 = path.join(MODEL_DIRECTORY, model_40.h5')

**Comment by marcelotduarte** [comment]
Please look at https://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files

**Comment by Lucysmith8** [comment]
I read the file before launching the issue, and I reproduced the exact same code.

> Please look at https://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files

I read the file before launching the issue, and I reproduced the exact same code.

**Comment by Lucysmith8** [comment]
I read the file before launching the issue, and I reproduced the exact same code.

**Comment by marcelotduarte** [comment]
If you can, put some print() or breakpoint() to inspect the value of your variables. Apparently `module.__file__` is None

**Comment by Lucysmith8** [comment]
When I run the program with cx freeze, there is no console, so how can I display the result of beakpoint ()?

**Comment by Lucysmith8** [comment]
This is the function used :
def get_parent_dir(module):
  return os.path.abspath(os.path.join(os.path.dirname(module.__file__), ".."))

**Comment by Lucysmith8** [comment]
Normally it should be fine, because module .__ file__ corresponds to model.model_40.h5, but I don't understand.

**Comment by marcelotduarte** [comment]
Run the executable from de command prompt, so you can see the result of print().
put a print(module) and print(module.__file__) to see the results.

**Comment by Lucysmith8** [comment]
I add print to the get_parent_dir function? But how do I launch an executable from the command prompt ?
